### ISSUE TITLE
MongoDb Zabbix Script do not work with SSL

### ISSUE THREAD

**Issue by denisgolius** [denisgolius/zabbix-mongodb#1]
@Genacvali 

> Hello,
> 
> There is the problem related to zabbix-mongodb.py script.
> Script is not working when the SSL configurations is enabled on MongoDB. As I realized there is no any SSL connection configurations in the script.
> The MongoDB version is 4.0+ and 4.2+
> The Zabbix vesrion is 4+
> If you have any addtional question - please let me know
> 
> Thank you

**Comment by denisgolius** [comment]
@Genacvali what kind of ssl you use: are they self signed or like letsencrypt/etc ?

**Comment by Genacvali** [comment]
@denisgolius We use not self signed ssl. to connect to mongoDB from shell we use root **ca.pem** and generated **mongo.pem**

here is the configuration of conf file with ssl

  ssl:
     mode: requireSSL
     PEMKeyFile: /ssl/mongodb.pem
     CAFile: /ssl/ca.pem

Here is connections string

 --ssl --sslPEMKeyFile=/ssl/mongodb.pem --sslCAFile /ssl/ca.pem

**Comment by Genacvali** [comment]
Hello

Any updates? Maybe there are any info require from my side?
Please let me know

**Comment by Genacvali** [comment]
Hello Denis

Resolved issue with this

else:
                try:
                    self.__conn = MongoClient(**'mongodb://admin:admin@mngdb01:11100/admin?replicaSet=prodCluster&tls=true&tlsCertificateKeyFile=/ssl/mongodb.pem&tlsCAFile=/ssl/ca.pem'**)
                except errors.PyMongoError as py_mongo_error:
                    print('Error in MongoDB connection: %s' %
                          str(py_mongo_error))
dut now the following issue

**[root@mngdb01 bin]# ./mongodb-stats.sh
Response from "127.0.0.1:10051": "processed: 0; failed: 43; total: 43; seconds spent: 0.000354"
Response from "*****:10051": "processed: 0; failed: 43; total: 43; seconds spent: 0.000328"
sent: 43; skipped: 0; total: 43
You have new mail in /var/spool/mail/root**


And no any metrics in zabbix

![image](https://user-images.githubusercontent.com/52817651/71984429-df5a8e80-3239-11ea-8d1e-136144f9c4f6.png)

**Comment by denisgolius** [comment]
I think, that your zabbix need more time to collect  data, also you can try to get some metric by zabbix_get from zabbix server
https://www.zabbix.com/documentation/3.0/manpages/zabbix_get

**Comment by Genacvali** [comment]
Could you please clarify - does this template works with mongoDb 4.2+ properly?
Looks like some metrics are depricated. Such as
**mongodb.get_server_status_metrics()** in **zabbix-mongodb.py**

I've commented this line in script due to error

**[root@mngdb01 bin]# ./mongodb-stats.sh
Traceback (most recent call last):
  File "/etc/zabbix/zabbix-mongodb/bin/zabbix-mongodb.py", line 243, in <module>
    mongodb.get_server_status_metrics()
  File "/etc/zabbix/zabbix-mongodb/bin/zabbix-mongodb.py", line 181, in get_server_status_metrics
    self.add_metrics('mongodb.memory.' + k, ss['mem'][k])
KeyError: 'mapped'**

Could you please review this issue?
And thank you for link, I will review and let you know if it helped
