### ISSUE TITLE
Not able to load any data from the mongo installation

### ISSUE THREAD

**Issue by hschoenh** [denisgolius/zabbix-mongodb#6]
Value "sh: /etc/zabbix/scripts/zabbix-mongodb-stats.sh: No such file or directory" of type "string" is not suitable for value type "Numeric (unsigned)"

Any advises?

**Comment by denisgolius** [comment]
> Value "sh: /etc/zabbix/scripts/zabbix-mongodb-stats.sh: No such file or directory" of type "string" is not suitable for value type "Numeric (unsigned)"
> 
> Any advises?

change type of value from Numeric to other?

**Comment by julenAlbi** [comment]
It seems */etc/zabbix/scripts/zabbix-mongodb-stats.sh* doesn't exists. Make sure after executing `install.sh` script, *zabbix-mongodb-stats.sh* is located in */etc/zabbix/scripts* (`ls /etc/zabbix/scripts`).

**Comment by hschoenh** [comment]
yes youre right, the .sh was wrong. chaning it come with another error.

Value "Traceback (most recent call last):
File "/etc/zabbix/scripts/zabbix-mongodb.py", line 245, in <module>
mongodb.get_db_names()
File "/etc/zabbix/scripts/zabbix-mongodb.py", line 73, in get_db_names
db_handler = self.__conn[self.mongo_db[0]]
TypeError: 'NoneType' object has no attribute '__getitem__'
info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000024"
sent: 1; skipped: 0; total: 1" of type "string" is not suitable for value type "Numeric (unsigned)"

Just configure that part of the phyton.

class MongoDB(object):
    """main script class"""
    # pylint: disable=too-many-instance-attributes
    def __init__(self):
        self.mongo_host = "127.0.0.1"
        self.mongo_port = 27017
        self.mongo_db = ["admin", ]
        self.mongo_user = "myuser"
        self.mongo_password = "myPassword"
        self.__conn = None
        self.__dbnames = None
        self.__metrics = []

**Comment by hschoenh** [comment]
Any recommendations?
